Port internal test for ThreadSafeStackContext
From internal ticket by @sema:

With the help of @recht, I've found a race (or unexpected semantics if you will) in Tornado's StackContext used by tornado-extras' RequestContext.

In short, StackContext more or less assumes it will only be expected on one thread. If you use it across threads (using wraps) then the context may be entered/exited in unexpected ways. This causes exceptions in RequestContext [like below], and other subtle errors.

```
AttributeError: 'RequestContextManager' object has no attribute '_prev_data'
```

I've included an explanation of the race(s) in the diff + a test case that triggers the error (revert the usage of ThreadSafeStackContext and the test should fail).

Signed-off-by: Yuri Shkuro <ys@uber.com>